import type { CategoryImage } from "@bw-bikes/shared";
import { type Document, model, Schema } from "mongoose";
import { categoryImageSchema } from "./schemas/category-image.schema.js";

export const MAX_BRAND_NAME_LENGTH = 60;
export const MAX_BRAND_DESCRIPTION_LENGTH = 400;

export interface IBrand extends Document {
  name: string;
  /** Autogenerated from `name` (`slugify`) — the one thing `Bike`/`Accessory.brand` references by id, and what the admin's brand filter actually sends. */
  slug: string;
  description?: string;
  /** Rendered attenuated (opacity/greyscale) by the UI — one asset, no separate pre-dimmed variant. */
  logo?: CategoryImage;
  order: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * One collection shared by both catalogs — a brand sells bikes and
 * accessories alike, so splitting it per tree (the way categories are split)
 * would just force the same brand to be created twice. `Bike.brand` and
 * `Accessory.brand` both reference this collection by id.
 */
const brandSchema = new Schema<IBrand>(
  {
    name: { type: String, required: true, trim: true, unique: true, maxlength: MAX_BRAND_NAME_LENGTH },
    slug: { type: String, required: true, unique: true, lowercase: true, trim: true },
    description: { type: String, trim: true, maxlength: MAX_BRAND_DESCRIPTION_LENGTH },
    logo: { type: categoryImageSchema, required: false },
    order: { type: Number, default: 0, min: 0 },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true },
);

brandSchema.index({ order: 1, name: 1 });

export const Brand = model<IBrand>("Brand", brandSchema);
